kind: pipeline
name: default

steps:
  - name: testing
    image: golang:1.16
    pull: true
    commands:
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./... ./pgtype/... ./ginproc/...
      - go vet ./... ./pgtype/... ./ginproc/...

  - name: wait-for-db
    image: postgres:11.2-alpine
    commands:
    - until pg_isready -q -U postgres -h database ; do sleep 1 ; echo -n "." ; done

  - name: testing-db
    image: golang:1.16
    pull: true
    commands:
      - git submodule init
      - git submodule update
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./... ./pgtype/... ./ginproc/...
      - go test -v -race -coverprofile=coverage.out -covermode=atomic -tags=db ./... ./pgtype/... ./ginproc/...
      - curl -s https://codecov.io/bash | bash
    environment:
      CODECOV_TOKEN:
        from_secret: my-codecov-token
      PGHOST:      database
      PGDATABASE:  test
      PGUSER:      postgres
      PGAPPNAME:   procapi

services:
  - name: database
    image: postgres:11.2-alpine
    ports:
    - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
